name: Bump Version
on: 
  workflow_dispatch:
  push:
    paths:
      - src
      - Dockerfile
      - nginx.conf
      - package.json
    branches: main


jobs:
  bump-node-version:
    name:  'Automated Version Bump'
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.version-bump.outputs.next_version }}

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: 'Automated Version Bump' 
        id: version-bump 
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
