name: Change Openshift Image Version
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to change to
        required: true
        default: latest

env: 
  HELM_CHART_NAME: vue-3
  OPENSHIFT_USER: jlangy2
  OPENSHIFT_NAMESPACE: jlangy2-dev
  IMAGE_NAME: vue-3-nginx
  
jobs:
  change-version:
    name:  Change openshift image version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1

        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
      
      - name: Upgrade helm
        working-directory: ./helm/vue-nginx
        run: |
          oc version
          helm upgrade ${{ env.HELM_CHART_NAME }} . --set image.tag=${{ github.event.inputs.tag }}
