name: fast lint and test
on: 
  push:
    branches-ignore: main
jobs:
  lint-test:  
    uses: jlangy/vue-3-nginx/.github/workflows/test-lint-reusable.yaml@main
    with: 
      installCommand: npm i
