name: Build Image in Github Packages
on: [workflow_dispatch ]

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: vue-3-nginx
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push To github
      id: push-to-github
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"